name: Deploy Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build/Deploy docs
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: recheck-io/vue-recheck-authorizer
        BUILD_SCRIPT: npm install && npm run build:docs
        BUILD_DIR: docs/.vuepress/dist/
